apiVersion: v1
kind: Service
metadata:
  name: myswa-api-service
  labels:
    app: myswa-api
spec:
  type: NodePort
  selector:
    app: myswa-api
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 31867