apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mariadb
  labels:
    app: mariadb
spec:
  serviceName: mariadb-service
  replicas: 1
  selector: 
    matchLabels:
      app: mariadb
  template: 
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: mariadb-volume
        persistentVolumeClaim:
          claimName: api-pvc
      - name: mariadb-initdb
        configMap:
          name: init-script
      containers:
        - env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: db-name
                name: db-credentials
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db-root-password
                name: db-credentials
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key:  db-username
                name: db-credentials
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key:  db-password
                name: db-credentials
          name: mariadb
          image: mariadb:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3306
          args: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--skip-innodb", "--default-storage-engine=myisam", "--default-tmp-storage-engine=myisam"]
          resources:
          volumeMounts:
          - name: mariadb-volume
            mountPath: /var/lib/mysql
          - name: mariadb-initdb
            mountPath: /docker-entrypoint-initdb.d
