apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  #type: NodePort
  selector:
    app: mariadb
  ports:
  - name: "6612"
    port: 6612
    targetPort: 3306
    #nodePort: 32760