# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - "*"
  #pull_request:
    #branches: [main]

jobs:
  build_action:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install -DskipTests
    - uses: actions/upload-artifact@main
      with:
        name: Project jar
        path: target/*.jar
    - uses: actions/kubeval-and-kubescore-for-kubernetes@v1
      with:
        files: test
        

    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
  test_action:
  
    runs-on: ubuntu-latest
    needs: build_action
    
    steps:
     - uses: actions/checkout@v2
     - uses: actions/download-artifact@main
       with:
        name: Project jar 
        path: target/*.jar
     - name: Test project
       run: mvn test
     - name: Test secrets
       run: echo ${{secrets.HOST}}
       
  deploy_action:
  
    if: contains( github.ref, 'main')
    runs-on: ubuntu-latest
    needs: test_action
    steps:
      - run: echo "Deploy to production server"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami
