apiVersion: v1
kind: ConfigMap
metadata:
  name: es-env
data:
  NODE_NAME: elastic
  CLUSTER_NAME: es-api-cluster
  BOOTSRAP_MEMORY_LOCK: "true"
  ES_JAVA_OPTS: -Xms512m -Xmx512m
  HTTP_CORS_ENABLED: "true"
  HTTP_CORS_ALLOW: "*"
  XPACK_SECURITY_ENABLED: "true"
  DISCOVERY_TYPE: single-node

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
  labels:
    app: elastic
spec:
  serviceName: es-service
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      volumes:
      - name: elastic-volume
        persistentVolumeClaim:
         claimName: api-pvc
      containers:
        - env:
          - name: node.name
            valueFrom:
              configMapKeyRef:
                key: NODE_NAME 
                name: es-env
          - name: cluster.name
            valueFrom:
              configMapKeyRef:
                key: CLUSTER_NAME
                name: es-env
          - name: bootstrap.memory_lock
            valueFrom:
              configMapKeyRef:
                key: BOOTSRAP_MEMORY_LOCK
                name: es-env
          - name: ES_JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                key: ES_JAVA_OPTS
                name: es-env
          - name: http.cors.enabled
            valueFrom:
              configMapKeyRef:
                key: HTTP_CORS_ENABLED
                name: es-env
          - name: http.cors.allow-origin
            valueFrom:
              configMapKeyRef:
                key: HTTP_CORS_ALLOW
                name: es-env
          - name: xpack.security.enabled
            valueFrom:
              configMapKeyRef:
                key: XPACK_SECURITY_ENABLED
                name: es-env
          - name: discovery.type
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_TYPE
                name: es-env
          - name: ELASTIC_USERNAME
            valueFrom:
              secretKeyRef:
                key: es-username
                name: es-credentials
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                key: es-password
                name: es-credentials
          name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9200
            name: http
          - containerPort: 9300
            name: transport
          resources:
            requests:
              cpu: 0.25
              memory: 1Gi
            limits:
              cpu: 0.50
              memory: 2Gi
      initContainers:
      -   name: init-es
          image: alpine:3.6
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
          - name: elastic-volume
            mountPath: /usr/share/elasticsearch/data
