apiVersion: v1
kind: Service
metadata:
  name: es-service
  labels:
    app: elastic
spec:
  #type: NodePort
  selector:
    app: elastic
  ports:
  - name: "18400"
    port: 18400
    targetPort: 9200
    #nodePort: 31003